### ISSUE TITLE
Improve Deploy Documentation

### ISSUE THREAD

**Issue by RoliesDonald** [craigmdennis/middleman-gulp-starter#28]
Hi, i'm new comer on front-end design and i'd like to start learning front-end design from middleman + gulp, can you explain how to deploy your repo to github page

**Comment by craigmdennis** [comment]
You can use the Gulp Deploy task included with Gulp Starter (and this repo).

I have a project that does exactly this https://github.com/craigmdennis/lpmotorsport. Pay attention to the `config.json` and the `package.json`

**Comment by RoliesDonald** [comment]
thank you so much.... for your fast response
