### ISSUE TITLE
Explore / demonstrate how the Gulp Starter rails helpers might work with Middleman

### ISSUE THREAD

**Issue by craigmdennis** [craigmdennis/middleman-gulp-starter#4]

**Comment by ryanlindsey** [comment]
I'm very interested in this as well. I was going to dig into this myself but would be happy to help if you're interested.

**Comment by craigmdennis** [comment]
@pixelsonly Feel free to experiment and post your findings. I've created the branch [`4_asset-helpers`](https://github.com/craigmdennis/middleman-gulp-starter/tree/4_asset-helpers)

**Comment by craigmdennis** [comment]
File revving is now working and the Rails helpers have been ported to Middleman.

Unexpected side-effect: The pre-revved files are copied to the build directory by Middleman.

Ideally we need a way to iterate through the `rev-manifest.json` and ignore those base files dynamically. It will get really annoying if someone has lots of files, as each file needs to be ignored manually at the moment.

**Comment by craigmdennis** [comment]
@pixelsonly Want to check out this branch and see it works for you?

**Comment by craigmdennis** [comment]
On a project with blogs I am now getting `no implicit conversion of nil into String` on [Line 16](https://github.com/craigmdennis/middleman-gulp-starter/pull/7/files#diff-05491fdce843f2173c12ad9d89206ae7R16) of the helper

**Comment by craigmdennis** [comment]
I'd missed off the extension. All good.
